### PR TITLE
Add Dockerfile that works for development use

### PR DESCRIPTION
**Pull request by Mr0grog**
Since it can be tough to get all the pieces installed and working right when using WSL on Windows, this dockerfile provides a way to develop and run the app in a container with all the necessary dependencies. You can build an image from it with:

    $ docker build -t data-covid19-sfbayarea .

And then run it via:

    # Get a bash prompt inside the container:
    $ docker run -it data-covid19-sfbayarea

    # Or instead just run the scraper in the
    # container and quit the container when the
    # scraper finishes:
    $ docker run -it data-covid19-sfbayarea python scraper_data.py --more args --here

@ldtcooper does this work for you? It might be better to test with the news scraper, since it seems like some of the data scrapers are broken at the moment.

### CODE REVIEW

**Comment by ldtcooper** [comment]
It seems to be working in that I'm no longer getting Selenium errors, and am instead getting Python errors whenever I try to run either scraper

**Comment by Mr0grog** [comment]
Were the news scraper errors #113? If so, seems like this is working great.

**Comment by ldtcooper** [comment]
This works for me!

**Comment by Mr0grog** [comment]
@ldtcooper how does this look? Added a quick helper script plus [docs](https://github.com/sfbrigade/data-covid19-sfbayarea/blob/dockerize-for-easier-windows-development/README.md#using-docker).

**Review by ldtcooper — APPROVED** [review]
This looks great! I'm looking forward to using it

**Pull request merged**
